import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "murgi chor app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="text-yellow-700 bg-gray-500 p-5">
        this is the header from login page
      </header>
      <body
        className={`font-bold text-purple-500`}
      >
        {children}
      </body>
      <footer className="text-green-800 p-10 bg-orange-200">
        this is the footer from auth
      </footer>
    </html>
  );
}
