import type { Metadata } from "next";

import ".././globals.css";

export const metadata: Metadata = {
  title: {
    default: "Marketing Page",
    template: "%s | Learning next js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="bg-yellow-700 text-gray-500 p-5">
        this is the header from login page
      </header>
      <body className={`font-bold text-purple-500`}>{children}</body>
      <footer className="bg-green-800 p-10 text-orange-200">
        this is the footer from auth
      </footer>
    </html>
  );
}
